### ISSUE TITLE
az container create error

### ISSUE THREAD

**Issue by RKauf00** [Azure-Samples/azure-government-openai-access#2]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> follow listed steps in readme, when completing the **az container create** command, the error message below is returned.

### Any log messages given by the failure
> (InaccessibleImage) The image 'agoacontainer/agoa:v1' in container group 'agoa' is not accessible. Please check the image and registry credential.
Code: InaccessibleImage
Message: The image 'agoacontainer/agoa:v1' in container group 'agoa' is not accessible. Please check the image and registry credential.

### Expected/desired behavior
> Container would be created in ACR

### OS and Version?
> Windows 11 Pro

### Versions
> 22H2

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by robcamer** [comment]
Check out my PR with an updated README.md to see if it helps. Thanks!  https://github.com/Azure-Samples/azure-government-openai-access/pull/4

**Comment by RKauf00** [comment]
I'll check out the update, thanks. I did have the admin account enabled and tested it with the `docker login` command.

**Comment by RKauf00** [comment]
Tested the new steps; received three errors.
1. `docker run` returned *TERM environment variable not set.* then showed a statement "I'm opening an ice creatm shop..." followed by a traceback (see below).
2. `az container create` returned `unrecognized arguments: agoa`. Removing agoa from the end of the statement returned `(InaccessibleImage) The image 'myagoaacrcontainer.azurecr.us/agoa:v1' in container group 'agoa' is not accessible. Please check the image and registry credential.
Code: InaccessibleImage
Message: The image 'myagoaacrcontainer.azurecr.us/agoa:v1' in container group 'agoa' is not accessible. Please check the image and registry credential.`

`Traceback (most recent call last):
  File "//agoa.py", line 23, in <module>
    response = openai.Completion.create(engine=engine, prompt="Write a tagline for an ice cream shop.", max_tokens=100)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Requests to the Completions_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 4 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.`
